title: ISV Playbook
description: The ISV Playbook is designed to help ISVs navigate the Microsoft Partner Network and leverage the resources available to build, go-to-market, and sell with Microsoft.
theme: just-the-docs

url: https://isvplaybook.github.io

logo: "/assets/images/logo.png"

aux_links:
  Template Repository: https://github.com/isvplaybook/isvplaybook.github.io

nav_enabled: true
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

enable_copy_code_button: true

permalink: pretty

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    docs:

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Split pages into sections that can be searched individually
# Supports 1 - 6, default: 2
search.heading_level: 2

# Maximum amount of previews per search result
# Default: 3
search.previews: 3

# Maximum amount of words to display before a matched word in the preview
# Default: 5
search.preview_words_before: 5

# Maximum amount of words to display after a matched word in the preview
# Default: 10
search.preview_words_after: 5

# Set the search token separator
# Default: /[\s\-/]+/
# Example: enable support for hyphenated search words
search.tokenizer_separator: /[\s/]+/

# Display the relative url in search results
# Supports true (default) or false
search.rel_url: false

# Footer content
# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/isvplaybook/isvplaybook.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
